#!/usr/bin/env bash
#
# build-apps-json.sh
# ==================
# localllm/<app>/exapp.json を集約して localllm/apps.generated.json を生成する。
#
# 目的:
#   exapps-proxy(genai-local 側) は単一の apps.json を読む実装のため無改修のまま、
#   アプリ定義を「各アプリのディレクトリ」に分散管理できるようにする。
#   アプリ追加は localllm/<新app>/exapp.json を足して本スクリプトを再実行するだけ。
#
# 生成物:
#   - localllm/apps.generated.json
#       genai-local の docker-compose.yaml から exapps-proxy の /app/apps.json にマウントされる。
#   - localllm/govais.generated.env
#       VITE_APP_GOVAIS_FOR_HOMEPAGE を apps.generated.json から導出した env ファイル。
#       genai-web が env_file で取り込み、ホーム画面の「おすすめアプリ」一覧を生成する。
#       （docker-compose.yaml に VITE_APP_GOVAIS_FOR_HOMEPAGE をハードコードする必要が無くなる）
#
# 使い方:
#   bash build-apps-json.sh
#   (redeploy-all.sh の先頭からも自動で呼ばれる)
#
# 環境変数:
#   HOMEPAGE_TEAM_ID  govais の teamId（既定: 00000000-0000-0000-0000-000000000000）

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# common/localstack の2つ上が localllm/
LOCALLLM_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
OUT="${LOCALLLM_DIR}/apps.generated.json"
GOVAIS_OUT="${LOCALLLM_DIR}/govais.generated.env"
TEAM_ID="${HOMEPAGE_TEAM_ID:-00000000-0000-0000-0000-000000000000}"

if ! command -v jq >/dev/null 2>&1; then
  echo "ERROR: jq が必要です(brew install jq / apt-get install jq)。" >&2
  exit 1
fi

shopt -s nullglob
files=("${LOCALLLM_DIR}"/*/exapp.json)
if [ ${#files[@]} -eq 0 ]; then
  echo "ERROR: ${LOCALLLM_DIR}/*/exapp.json が1件も見つかりません。" >&2
  exit 1
fi

# 各 exapp.json ({exAppId: {...}}) を1つのオブジェクトにマージする。
# 同じ exAppId が複数あった場合は後勝ち(* の右側優先)。
jq -s 'reduce .[] as $a ({}; . * $a)' "${files[@]}" > "${OUT}"

echo "generated: ${OUT} (${#files[@]} app(s))"
for f in "${files[@]}"; do
  echo "  - ${f}"
done

# apps.generated.json から VITE_APP_GOVAIS_FOR_HOMEPAGE を導出して env ファイルを生成する。
# 形式: [{ "title", "teamId", "exAppId", "description" }, ...]
GOVAIS_JSON=$(jq -c --arg teamId "${TEAM_ID}" '
  to_entries
  | map({
      title: (.value.exAppName // .key),
      teamId: $teamId,
      exAppId: .key,
      description: (.value.description // "")
    })
' "${OUT}")

{
  echo "# Auto-generated by build-apps-json.sh from apps.generated.json"
  echo "# Do not edit manually. Re-run build-apps-json.sh to update."
  echo "VITE_APP_GOVAIS_FOR_HOMEPAGE=${GOVAIS_JSON}"
} > "${GOVAIS_OUT}"

echo "generated: ${GOVAIS_OUT}"
